<?php
namespace Food\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class FoodController extends AbstractActionController
{
	public function indexAction()
	{
		$grid = array(
			'shop'=>array(
				array(
					array(
						'name'=>'Salad', 
						'total'=>'1', 
						'remaining'=>'1', 
					),
					array(
						'name'=>'Soup', 
						'total'=>'2', 
						'remaining'=>'2', 
					),
				),
				array(),
				array(),
				array(),
				array(),
				array(),
				array(),
			),
			'prepare'=>array(
				array(
					array(
						'name'=>'Lasagna<br />Prep: 30 min<br />Cook: 60 min', 
						'total'=>'10', 
						'remaining'=>'10', 
					),
				),
				array(
					array(
						'name'=>'Salad<br />Prep: 5 min', 
						'total'=>'1', 
						'remaining'=>'1', 
					),
					array(
						'name'=>'Soup<br />Cook: 3 min', 
						'total'=>'2', 
						'remaining'=>'2', 
					),
				),
				array(),
				array(),
				array(),
				array(),
				array(),
			),
			'available'=>array(
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'10', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'9', 
					),
					array(
						'name'=>'Salad', 
						'total'=>'1', 
						'remaining'=>'1', 
					),
					array(
						'name'=>'Soup', 
						'total'=>'2', 
						'remaining'=>'2', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'8', 
					),
					array(
						'name'=>'Soup', 
						'total'=>'2', 
						'remaining'=>'1', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'2', 
					),
				),
				array(),
				array(),
				array(),
			),
			'eat'=>array(
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'1', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'1', 
					),
					array(
						'name'=>'Salad', 
						'total'=>'1', 
						'remaining'=>'1', 
					),
					array(
						'name'=>'Soup', 
						'total'=>'2', 
						'remaining'=>'1', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'6', 
					),
					array(
						'name'=>'Soup', 
						'total'=>'2', 
						'remaining'=>'1', 
					),
				),
				array(
					array(
						'name'=>'Lasagna', 
						'total'=>'10', 
						'remaining'=>'2', 
					),
				),
				array(),
				array(),
				array(),
			),
		);
		return new ViewModel(array(
			'grid'=>$grid,
		));
	}
}
